name: 'Morty Post Mortems'
description: 'Turns a repository into an organized collection of post-mortems'
branding:
  icon: archive
  color: blue
inputs:
  token:
    description: 'Github token ({{ github.token }}) to access the repository'
    required: true
runs:
  using: docker
  image: Dockerfile
